### ISSUE TITLE
Test with Lingua Franca test binaries

### ISSUE THREAD

**Issue by chanijjani** [hokeun/lf-rust-rti#30]

**Comment by chanijjani** [comment]
After merging the [PR](https://github.com/hokeun/lf-rust-rti/pull/35)
- [x] Absent.lf   --> Warnings are found.*
- [ ] AfterDelays.lf
- [ ] AfterDelaysWithMultiport.lf
- [x] BankIndex.lf
- [x] BroadcastFeedback.lf  --> Warnings are found.*
- [x] BroadcastFeedbackWithHierarchy.lf  --> Warnings are found.*
- [x] ChainWithDelay.lf  --> Warnings are found.*
- [ ] ClockSync.lf
- [ ] CycleDetection.lf  --> Warnings are found.*
- [ ] DecentralizedP2PComm.lf --> MsgType(14) MSG_TYPE_ADDRESS_ADVERTISEMENT is not implemented in Rust RTI.
- [ ] DecentralizedP2PSTPViolation.lf --> MsgType(14) MSG_TYPE_ADDRESS_ADVERTISEMENT is not implemented in Rust RTI.
- [ ] DecentralizedP2PUnbalancedTimeout.lf
 --> Couldn't run C RTI + MsgType(14) MSG_TYPE_ADDRESS_ADVERTISEMENT is not implemented in Rust RTI.
- [ ] DecentralizedP2PUnbalancedTimeoutPhysical.lf
 --> Couldn't run C RTI + MsgType(14) MSG_TYPE_ADDRESS_ADVERTISEMENT is not implemented in Rust RTI.
- [x] DistributedBank.lf
- [x] DistributedBankToMultiport.lf  --> Warnings are found.*
- [x] DistributedCount.lf
- [ ] DistributedCountDecentralized.lf  --> Couldn't run C RTI + Hanging in Rust RTI.
- [ ] DistributedCountDecentralizedLate.lf  --> Couldn't run C RTI + Hanging in Rust RTI.
- [ ] DistributedCountDecentralizedLateHierarchy.lf
  --> Couldn't run C RTI + MsgType(14) MSG_TYPE_ADDRESS_ADVERTISEMENT is not implemented in Rust RTI.
- [ ] DistributedCountPhysical.lf
  --> Couldn't run C RTI + MsgType(14) MSG_TYPE_ADDRESS_ADVERTISEMENT is not implemented in Rust RTI.
- [ ] DistributedCountPhysicalAfterDelay.lf
  --> Couldn't run C RTI + MsgType(14) MSG_TYPE_ADDRESS_ADVERTISEMENT is not implemented in Rust RTI.
- [ ] DistributedCountPhysicalDecentralized.lf
  --> Couldn't run C RTI + Rust RTI panic occurs as follows.
```
thread 'main' panicked at src/server.rs:66:49:
called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
```
- [x] DistributedDoublePort.lf  --> Warnings are found.*
- [ ] DistributedDoublePortLooped.lf  --> Rust RTI panic occurs as follows.
```
thread '<unnamed>' panicked at src/server.rs:934:25:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at src/rti_common.rs:751:52:
```
- [ ] DistributedDoublePortLooped2.lf
- [x] DistributedInterleaved.lf
- [ ] DistributedLogicalActionUpstreamLong.lf
- [x] DistributedLoopedAction.lf
- [ ] DistributedLoopedActionDecentralized.lf
- [ ] DistributedLoopedPhysicalAction.lf
- [ ] DistributedLoopedPhysicalActionDecentralized.lf
- [x] DistributedMultiport.lf
- [x] DistributedMultiportToBank.lf
- [x] DistributedMultiportToken.lf
- [x] DistributedNetworkOrder.lf
- [x] DistributedPhysicalActionUpstream.lf
- [x] DistributedPhysicalActionUpstreamLong.lf
- [x] DistributedStop.lf
- [ ] DistributedStopDecentralized.lf
- [x] DistributedStopZero.lf
- [ ] DistributedStopZeroDecentralized.lf
- [ ] DistributedToken.lf
- [x] EnclaveFederatedRequestStop.lf
- [x] FederatedFilePkgReader.lf
- [x] FederatedFileReader.lf
- [x] FeedbackDelay.lf
- [ ] FeedbackDelay2.lf
- [x] FeedbackDelay3.lf
- [ ] FeedbackDelay4.lf
- [x] FeedbackDelay5.lf
- [ ] FeedbackDelay6.lf
- [x] FeedbackDelaySimple.lf
- [x] HelloDistributed.lf
- [x] InheritanceFederated.lf
- [ ] InheritanceFederatedImport.lf
- [ ] LevelPattern.lf
- [x] LoopDistributedCentralized.lf
- [x] LoopDistributedCentralized2.lf
- [x] LoopDistributedCentralizedPhysicalAction.lf
- [x] LoopDistributedCentralizedPrecedence.lf
- [x] LoopDistributedCentralizedPrecedenceHierarchy.lf
- [ ] LoopDistributedDecentralized.lf
- [ ] LoopDistributedDecentralizedPrecedence.lf
- [ ] LoopDistributedDecentralizedPrecedenceHierarchy.lf
- [ ] LoopDistributedDouble.lf
- [ ] MultipleSTP.lf
- [x] ParallelDestinations.lf
- [x] ParallelSources.lf
- [x] ParallelSourcesMultiport.lf
- [ ] PhysicalSTP.lf
- [ ] PingPongDistributed.lf
- [ ] PingPongDistributedPhysical.lf
- [ ] STPParameter.lf
- [x] SimpleFederated.lf
- [ ] SimpleFederatedAuthenticated.lf
- [ ] SmallDelayDecentralized.lf
- [x] SpuriousDependency.lf
- [x] StopAtShutdown.lf
- [x] TopLevelArtifacts.lf

*Warning
```
WARNING!!! min_upstream_completed.time() < start_time
```

**Comment by chanijjani** [comment]
Enabled **four more examples** --> DecentralizedP2PComm.lf, DecentralizedP2PSTPViolation.lf, DecentralizedP2PUnbalancedTimeout.lf, DecentralizedP2PUnbalancedTimeoutPhysical.lf

**Comment by chanijjani** [comment]
I enabled **five more examples** in our integration tests after testing: **DistributedCountDecentralizedLate.lf, DistributedCountDecentralizedLateHierarchy.lf, DistributedCountPhysical.lf, DistributedCountPhysicalAfterDelay.lf, DistributedCountPhysicalDecentralized.lf**  -->  (43/87)

**Comment by chanijjani** [comment]
I enabled **seven more examples** in our integration tests after testing; **AfterDelay.lf, AfterDelaysWithMultiport.lf, ChainWithDelay.lf, CycleDetection.lf, DistributedCount.lf, DistributedLoopedActionDecentralized.lf and DistributedMultiportToken.lf** --> (50/87)

**Comment by chanijjani** [comment]
After testing, I enabled **six more examples** in our integration tests: **MultipleSTP.lf, PhysicalSTP.lf, PingPongDistributed.lf, PingPongDistributedPhysical.lf, STPParameter.lf, and SmallDelayDecentralized.lf** --> (56/87)

**Comment by chanijjani** [comment]
After testing, I enabled **five more examples** in our integration tests: **LoopDistributedDecentralized.lf, LoopDistributedDouble.lf, DistributedStop.lf, DistributedStopDecentralized.lf, and DistributedToken.lf**  -->  (61/87)

**Comment by chanijjani** [comment]
After testing, I enabled **two more examples** in our integration tests: **BankIndex.lf and ClockSync.lf**  -->  (63/87)
